server:
  port: 9200


spring:
  rabbitmq:
    virtual-host: /
    host: gzhen
    port: 5672
    username: gzhen
    password: gzhen
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mq_db?serverTimezone=GMT%2B8
