server:
  port: 9100

spring:
  application:
    name: nacos-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public