server:
  port: 9100

spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver