server:
  port: 9100
spring:
  application:
    name: zipkin-sleuth-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        password: nacos
        username: nacos
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
  file:
    name: d:/abc/zipkin_sleuth_order.log
